// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpcwXgw45PZY3eQIFu7apObM-iiXasHA0',
    appId: '1:510837727133:web:4b80a4de77c04e2ed11974',
    messagingSenderId: '510837727133',
    projectId: 'startupx-eda61',
    authDomain: 'startupx-eda61.firebaseapp.com',
    storageBucket: 'startupx-eda61.appspot.com',
    measurementId: 'G-XF6JEMR5EN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp6n7cWeDGbzxGZRjHHQ7QnHx4VkZ95_s',
    appId: '1:510837727133:android:c4c1de88bd8b277fd11974',
    messagingSenderId: '510837727133',
    projectId: 'startupx-eda61',
    storageBucket: 'startupx-eda61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFayrM_0Am2jI10Whz_bywbiKEfm0Lb50',
    appId: '1:510837727133:ios:df3d4f70aefc3f2cd11974',
    messagingSenderId: '510837727133',
    projectId: 'startupx-eda61',
    storageBucket: 'startupx-eda61.appspot.com',
    iosClientId: '510837727133-bn7slblohipmtfmnuti7cvno7tm4o13o.apps.googleusercontent.com',
    iosBundleId: 'com.example.startupx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFayrM_0Am2jI10Whz_bywbiKEfm0Lb50',
    appId: '1:510837727133:ios:df3d4f70aefc3f2cd11974',
    messagingSenderId: '510837727133',
    projectId: 'startupx-eda61',
    storageBucket: 'startupx-eda61.appspot.com',
    iosClientId: '510837727133-bn7slblohipmtfmnuti7cvno7tm4o13o.apps.googleusercontent.com',
    iosBundleId: 'com.example.startupx',
  );
}
